name: lint,test,build
on: push

jobs:
    integrate:
        runs-on: ubuntu-latest
        steps:
          - name: get code
            uses: actions/checkout@v3
          - name: install dependencies
            uses: npm ci
          - name: lint code
            uses: npm run lint
          - name: test code
            uses: npm test
          - name: build code 
            uses: npm run build



