name: lint,test,build
on: push

jobs:
    integrate:
        runs-on: ubuntu-latest
        steps:
          - name: get code
            uses: actions/checkout@v3
          - name: install dependencies
            run: npm ci
          - name: lint code
            run: npm run lint
          - name: test code
            run: npm test
          - name: build code 
            run: npm run build



