name: metadata
on:
    issues:
        types: [opened]
    workflow_dispatch:
        inputs:
            name:
                description: 'Name'
                required: true

jobs:
    metadata:
        runs-on: ubuntu-latest
        steps:
            - name: output github context or metadata
              run: echo "${{ toJson(github) }}"
            